name: webapp deployment

on:
  push:
    branches:
      - main
  
  workflow_dispatch:


jobs:
  deployment:
    runs-on: ubuntu-latest
    steps: 
      - name: compilation java code start
        run: echo "starting code compilation"
        shell: bash
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          token: ${{secrets.GITHUB_TOKEN}}
      
      - name: compile Code
        run: |
          javac -cp "lib/*"  WEB-INF/classes/*.java
      
      - name: convert into war file
        run: |
          mkdir target
          jar -cvf target/deployment.war *
      
      - name: private key 
        run: |
          echo "${{secrets.PRIVATE_KEY}}" > private.pem
          sudo chmod 600 private.pem
      
      - name: copying to deployment machine
        run: |
          scp -o StrictHostKeyChecking=no -i private.pem target/deployment.war ec2-user@ec2-18-204-215-43.compute-1.amazonaws.com:/home/ec2-user/
      
